// Builds the Saudi Arabia outline used by the backoffice "Real time" dashboard: country border (Natural Earth's Saudi
// Arabia point-of-view edition), the 13 region borders and the neighbouring countries, simplified and projected to SVG
// paths in one small module. Natural Earth is public domain. Run again only to change the look or the source.
//   npm run map:saudi        -> ../src/EHC.Web/wwwroot/App_Plugins/EhcStats/saudi-map.js
// Source files are downloaded into frontend/.tools/ne (git-ignored); mapshaper runs through npx.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const NE = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson';
const dir = resolve('.tools/ne');
const out = resolve(process.env.MAP_OUT || '../src/EHC.Web/wwwroot/App_Plugins/EhcStats/saudi-map.js');
const NEIGHBOURS = ['IRQ', 'JOR', 'KWT', 'BHR', 'QAT', 'ARE', 'OMN', 'YEM', 'EGY', 'SDN', 'ERI', 'ISR', 'PSE', 'SYR', 'IRN'];
// view: the whole kingdom with a margin; equirectangular, x scaled by cos(24°) so shapes are not stretched
const [W_LON, S_LAT, E_LON, N_LAT] = [34, 15.6, 56.4, 32.8];
const WIDTH = 1000;
const COS = Math.cos((24 * Math.PI) / 180);
const K = WIDTH / ((E_LON - W_LON) * COS);
const HEIGHT = Math.round((N_LAT - S_LAT) * K);
const SIMPLIFY = 'interval=1500';

async function source(name) {
  const file = resolve(dir, `${name}.geojson`);
  if (!existsSync(file)) {
    console.log(`downloading ${name} …`);
    const res = await fetch(`${NE}/${name}.geojson`);
    if (!res.ok) throw new Error(`download failed (${res.status}): ${name}`);
    writeFileSync(file, Buffer.from(await res.arrayBuffer()));
  }
  return file;
}

function mapshaper(...args) {
  const win = process.platform === 'win32';
  // npx is a .cmd file on Windows, which needs a shell; the shell gets the arguments as typed, so quote them
  const quoted = win ? args.map((a) => (/[\s'()=,]/.test(a) ? `"${a}"` : a)) : args;
  execFileSync(win ? 'npx.cmd' : 'npx', ['--yes', 'mapshaper@0.6', ...quoted], { stdio: ['ignore', 'ignore', 'inherit'], shell: win });
}

const fmt = (n) => (Math.round(n * 10) / 10).toString();
const point = ([lon, lat]) => `${fmt((lon - W_LON) * COS * K)},${fmt((N_LAT - lat) * K)}`;

/** All geometries of a GeoJSON file as one SVG path ("Z" closes polygon rings; lines stay open). */
function path(file) {
  const rings = [];
  const add = (geometry) => {
    if (!geometry) return;
    const { type, coordinates: c } = geometry;
    if (type === 'Polygon') c.forEach((r) => rings.push('M' + r.map(point).join('L') + 'Z'));
    else if (type === 'MultiPolygon') c.forEach((p) => p.forEach((r) => rings.push('M' + r.map(point).join('L') + 'Z')));
    else if (type === 'LineString') rings.push('M' + c.map(point).join('L'));
    else if (type === 'MultiLineString') c.forEach((l) => rings.push('M' + l.map(point).join('L')));
    else if (type === 'GeometryCollection') geometry.geometries.forEach(add);
  };
  const json = JSON.parse(readFileSync(file, 'utf8'));
  // mapshaper writes a bare GeometryCollection when the features have no attributes (e.g. after -innerlines)
  if (json.type === 'FeatureCollection') json.features.forEach((f) => add(f.geometry));
  else add(json.type === 'Feature' ? json.geometry : json);
  return rings.join('');
}

mkdirSync(dir, { recursive: true });
const countries = await source('ne_10m_admin_0_countries_sau');
const regions = await source('ne_10m_admin_1_states_provinces');
const tmp = (n) => resolve(dir, `${n}.out.json`);
const bbox = `bbox=${W_LON},${S_LAT},${E_LON},${N_LAT}`;

mapshaper('-i', countries, '-filter', "ADM0_A3 == 'SAU'", '-simplify', SIMPLIFY, 'keep-shapes', '-o', 'format=geojson', tmp('country'));
mapshaper('-i', countries, '-filter', `[${NEIGHBOURS.map((c) => `'${c}'`).join(',')}].indexOf(ADM0_A3) > -1`, '-clip', bbox, '-simplify', SIMPLIFY, '-o', 'format=geojson', tmp('neighbours'));
mapshaper('-i', regions, '-filter', "adm0_a3 == 'SAU'", '-innerlines', '-simplify', SIMPLIFY, '-o', 'format=geojson', tmp('regions'));

writeFileSync(out, `/* Saudi Arabia outline for the "Real time" dashboard. Generated by frontend/scripts/saudi-map.mjs from Natural Earth
   (public domain, Saudi Arabia point-of-view borders); do not edit by hand. */
export const WIDTH = ${WIDTH};
export const HEIGHT = ${HEIGHT};

/** SVG position of a latitude / longitude. */
export function project(lat, lon) {
  return [(lon - ${W_LON}) * ${COS.toFixed(6)} * ${K.toFixed(4)}, (${N_LAT} - lat) * ${K.toFixed(4)}];
}

export const COUNTRY = '${path(tmp('country'))}';
export const REGION_LINES = '${path(tmp('regions'))}';
export const NEIGHBOURS = '${path(tmp('neighbours'))}';
`);
console.log(`wrote ${out}`);
